$ ->
  windowWidth = window.innerWidth
  if windowWidth >= 768
    $('.dropdown-content', this).hide()
    $('.dropdown-parent').hover (->
      $('.dropdown-content', this).show()
      return
    ), ->
      $('.dropdown-content', this).hide()
      return
  else
    $('.top_menu', this).hide()
    $('.global_nav').click ->
      $('.top_menu', this).toggle()
      return
  return

# ---
# generated by js2coffee 2.2.0