window.addEventListener 'resize', ->
  # ????????????????????
  if typeof($)=="undefined"
    return
  windowWidth = window.innerWidth
  if windowWidth >= 768
    $('.dropdown-content').hide()
    $('.dropdown-parent').hover (->
      $('.dropdown-content').show()
      return
    ), ->
      $('.dropdown-content').hide()
      return
    $('.top_menu').show()
  else
    $('.top_menu').hide()
    $('.global_nav').click ->
      $('.top_menu').toggle()
      return
  return

window.addEventListener 'load', ->
  $(window).trigger("resize")

# ---
# generated by js2coffee 2.2.0