class Parser
  getItems: (json)->
    return json

  getLink: (items,i)->
    return ""

  getTitle: (items,i)->
    return ""

  getSummaryTitle: (items)->
    return ""

  getSummaryLink: (items)->
    return ""

  hashCode: (str)->
    hash = 0
    i = undefined
    chr = undefined
    if str.length == 0
      return hash
    i = 0
    while i < str.length
      chr = str.charCodeAt(i)
      hash = (hash << 5) - hash + chr
      hash |= 0
      # Convert to 32bit integer
      i++
    hash

  addRssItem: (json, rssbox)->
    if json.length == 0
      return

    rss_items = @getItems(json)

    len = rss_items.length
    if len > 10
      len = 10

    root = rssbox.getElementsByClassName('rss-items')[0]
    template = root.getElementsByTagName('template')[0]

    i = 0
    while i < len
      #複製してliタグを得る
      new_li = document.importNode(template.content, true).firstElementChild
      new_a = new_li.firstElementChild
      new_a.setAttribute 'href', @getLink(rss_items,i)
      new_a.innerHTML = @getTitle(rss_items,i)
      random = @hashCode(@getTitle(rss_items,i))
      detail = 
        'content_type': 'product'
        'items': [ {
          'id': '' + random
          'name': @getTitle(rss_items,i)
        } ]
      gtag_text = 'gtag(\'event\',\'select_content\', ' + JSON.stringify(detail) + ')'
      new_a.setAttribute 'onclick', gtag_text
      root.appendChild new_li
      i++
    summary_tag = rssbox.getElementsByClassName('summary')
    if summary_tag.length == 1
      summary = summary_tag[0]
      summary.setAttribute 'href', @getSummaryLink(json)
      summary.innerHTML = @getSummaryTitle(json)
    progress = rssbox.getElementsByTagName('progress')[0]
    progress.style.display = 'none'
    return

class RssParser extends Parser
  getItems: (json)->
    if typeof json['@attributes'] == 'undefined'
      rss_items = json['item']
    else
      rss_items = json['channel']['item']
    #rss_itemが一つしか存在しない場合、配列で取得できない
    if !Array.isArray(rss_items)
      rss_items = [ rss_items ]
    return rss_items

  getLink: (items,i) ->
    return items[i]['link']

  getTitle: (items,i)->
    return items[i]['title']

  getSummaryTitle: (json)->
    return json['channel']['title']

  getSummaryLink: (json)->
    return json['channel']['link']

window.addEventListener 'load', (->
  rssboxs = document.getElementsByClassName('rss-box')
  i = 0
  while i < rssboxs.length
    #無名関数を使わないとajaxが意図したとおりに実行されない
    do (i) ->
      rssbox = rssboxs[i]
      rss_url = rssbox.getAttribute('data-rss-url')
      $.ajax
        type: 'GET'
        url: '/rss/index.php?rss_url=' + rss_url
        dataType: 'json'
        success: (json) ->
          parser = new RssParser
          parser.addRssItem(json, rssbox)
          return
      return
    i++
  return
), false

# ---
# generated by js2coffee 2.2.0