# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: cowcowhomes.ltd
subtitle: ''
description: ''
keywords:
author: cowcowhomes
language: [ja,en]
timezone: ''

url: https://www.cowcowhomes.com
root: /
permalink: :language/:year/:month/:day/:title/
new_post_name: :language/:year/:month/:day/:title.md
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: bizvektor

highlight:
  enable: true
  line_number: false

# デフォルトだといくつかのファイルがコピーされない
include:
  - .htaccess
  - "image/**/*"

marked:
  prependRoot: true
  postAsset: true

